{
 "title": "Aggregate Metrics Dashboard",
 "description": "Monitors Kubernetes deployments in cluster using Prometheus. Shows overall cluster CPU / Memory of deployments, replicas in each deployment. Uses Kube state metrics and cAdvisor metrics (741)",
 "tags": [
  "kubernetes",
  "deployment"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Deployment", "query": "label_values(deployment)" },
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   },
   { "name": "Namespace", "label": "Namespace" }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"^$Deployment$.*$\", kubernetes_io_hostname=~\"^$Node$\"}) / sum (kube_node_status_allocatable{pod=~\"^$Deployment.*$\",node=~\"^$Node$\", resource=\"memory\", unit=\"byte\"}) * 100",
     "legendFormat": "Actual"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", pod=~\"^$Deployment.*$\", kubernetes_io_hostname=~\"^$Node$\"}) / sum (kube_node_status_allocatable{node=~\"^$Node.*$\", resource=\"memory\", unit=\"byte\"}) * 100",
     "legendFormat": "Requested"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod=~\"^$Deployment.*$\", kubernetes_io_hostname=~\"^$Node$\"}[1m])) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"}) * 100",
     "legendFormat": "Actual"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", kubernetes_io_hostname=~\"^$Node$\",pod=~\"^$Deployment.*$\"}) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"}) * 100 ",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum (kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\", kubernetes_io_hostname=~\"^$Node$\",pod=~\"^$Deployment.*$\"}) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"}) * 100 ",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Unavailable Replicas",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(kube_deployment_status_replicas{deployment=~\".*$Deployment\"}) or vector(0)) - (sum(kube_deployment_status_replicas_available{deployment=~\".*$Deployment\"}) or vector(0))) / (sum(kube_deployment_status_replicas{deployment=~\".*$Deployment\"}) or vector(0))  * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod_name=~\"^$Deployment.*$\", kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_node_status_allocatable{node=~\"^$Node.*$\", resource=\"memory\", unit=\"byte\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod=~\"^$Deployment.*$\", kubernetes_io_hostname=~\"^$Node$\", namespace=~\"$Namespace.*$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Available (cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kube_deployment_status_replicas_available{deployment=~\".*$Deployment\"}) or vector(0))"
    }
   ]
  },
  {
   "title": "Total (cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kube_deployment_status_replicas{deployment=~\".*$Deployment\"}) or vector(0)) ",
     "legendFormat": "{{ $Daemonset }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{io_kubernetes_container_name!=\"POD\",pod=~\"^$Deployment.*$\",kubernetes_io_hostname=~\"^$Node$\"}[2m]))",
     "legendFormat": "Actual"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",pod=~\"^$Deployment.*$\",node=~\"^$Node$\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum (kube_node_status_allocatable{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"^$Deployment.*$\",kubernetes_io_hostname=~\"^$Node$\"})",
     "legendFormat": "Actual"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests{pod=~\"^$Deployment.*$\",node=~\"^$Node$\", resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum (kube_node_status_allocatable{pod=~\"^$Deployment.*$\",node=~\"^$Node$\", resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{pod=~\"^$Deployment.*$\",kubernetes_io_hostname=~\"^$Node$\"}[1m]))",
     "legendFormat": "-> {{ pod }}"
    },
    {
     "expr": "- sum( rate (container_network_transmit_bytes_total{pod=~\"^$Deployment.*$\",kubernetes_io_hostname=~\"^$Node$\"}[1m]))",
     "legendFormat": "<-  {{ pod_name }}"
    }
   ]
  }
 ]
}