{
 "title": "test",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info, pod)"
   },
   {
    "name": "Pod_ip",
    "query": "label_values(kube_pod_info, pod_ip)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pod IP Address",
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "content": "# $Pod_ip" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pod Status",
   "type": "stat",
   "description": "1=Running.\n!!!=Not Running.",
   "gridPos": { "h": 5, "w": 9, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_status_phase{phase=\"Running\", pod=~\"^$Pod$\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container restarts",
   "type": "stat",
   "description": "!!! - Many Restarts",
   "gridPos": { "h": 5, "w": 9, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{pod=~\"$Pod.*$\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pod memory usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"^$Pod$\"}) / sum (kube_node_status_allocatable{kubernetes_io_hostname=~\"^$Node$\",resource=\"memory\", unit=\"byte\"}) * 100"
    }
   ]
  },
  {
   "title": "Pod CPU usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod=~\"^$Pod$\"}[1m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100",
     "legendFormat": "Usage Efficiency"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod=~\"^$Pod$\"}[1m])) / sum (kube_pod_container_resource_limits{kubernetes_io_hostname=~\"^$Node$\", resource='cpu'}) * 100",
     "legendFormat": "Allocation Efficiency"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"^$Pod$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (kube_node_status_allocatable{node=~\"^$Node.*$\", resource=\"memory\", unit=\"byte\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod=~\"^$Pod$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{kubernetes_io_hostname=~\"^$Node$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Pods CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pods CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod=~\"^$Pod$\"}[5m])) by (io_kubernetes_pod_name)",
     "legendFormat": "{{ io_kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"^$Pod$\"}) by (io_kubernetes_pod_name)",
     "legendFormat": "{{ io_kubernetes_pod_name }}"
    }
   ]
  }
 ]
}